# -*- coding: utf-8 -*-
"""Baseline Survival Model (v1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sQVUjlZEW51i5vcH906tOVveIx2aLvlh
"""

# Check Python version (optional, sanity)
import sys
print(sys.version)

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("v_survival_training (4).csv")
df.head()

df.info()

df.describe()

features = [
    "growth_rate_class",
    "drought_score",
    "fire_score",
    "disease_score",
    "planted_count",
]

X = df[features]
y = df["survival_ratio"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Absolute Error (MAE):", round(mae, 4))
print("R² Score:", round(r2, 4))

coef_df = pd.DataFrame({
    "feature": features,
    "coefficient": model.coef_
})

coef_df

for f, c in zip(features, model.coef_):
    print(f"{f}: {c:.4f}")

"""**RANDOM FOREST SURVIVAL MODEL (ML v1.1)**

This model is meant to:

* capture non-linear effects
* improve R²
* remain explainable
"""

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score

# X and y already defined earlier
X.head(), y.head()

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

rf_model = RandomForestRegressor(
    n_estimators=200,
    max_depth=6,
    min_samples_leaf=5,
    random_state=42
)

rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)

mae_rf = mean_absolute_error(y_test, y_pred_rf)
r2_rf = r2_score(y_test, y_pred_rf)

print("Random Forest MAE:", round(mae_rf, 4))
print("Random Forest R²:", round(r2_rf, 4))

importances = rf_model.feature_importances_

importance_df = pd.DataFrame({
    "feature": features,
    "importance": importances
}).sort_values(by="importance", ascending=False)

importance_df

for f, imp in zip(importance_df["feature"], importance_df["importance"]):
    print(f"{f}: {imp:.4f}")

print("Linear MAE:", round(mae, 4))
print("RF MAE:", round(mae_rf, 4))
print("Linear R²:", round(r2, 4))
print("RF R²:", round(r2_rf, 4))

import joblib
joblib.dump(rf_model, "rf_survival_v1_1.pkl")

