/**
 * CarbonSense — Public Type Exports
 * Re-exports all types from lib/types.ts for backwards compatibility.
 * Components can import from either '@/types' or '@/lib/types'.
 */

export type {
  Role,
  User,
  AuthState,
  EmployeeSignupRequest,
  ManagerConsent,
  EmissionCategory,
  EmissionEntry,
  EmissionSummary,
  DashboardMetrics,
  TreeSpecies,
  PlantingRecord,
  PolicyUrgency,
  Policy,
  PolicyAlert,
  RecommendationType,
  DifficultyLevel,
  Recommendation,
  NotificationType,
  Notification,
  UserRole,
  TeamMember,
  Permission,
  TimeSeriesData,
  CategoryBreakdown,
  ForecastData,
  OrganizationSettings,
  UserPreferences,
  ApiResponse,
  PaginatedResponse,
  FormFieldError,
  ValidationResult,
  ChartConfig,
  UploadedFile,
  FileUploadConfig,
  ComplianceStatus,
  ComplianceItem,
  DataSource,
  DataIngestionRecord,
  LoadingState,
  SortOrder,
  SortConfig,
  FilterConfig,
} from '@/lib/types';
